title: Intro to the HTRC
remote_theme: ubc-library-rc/rc-theme
color_scheme: rc
github_repo_url: "https://github.com/ubc-library-rc/intro-htrc"

# license information for workshop content
This workshop is adapted from Hathi Trust Research Center's training materials avilaable under a CC BY 4.0 license. [The most recent materials are available here](https://drive.google.com/drive/folders/1vQgrWTCjpWpEhoCUk2HY306N4O_UFAC4).
# required for building jekyll site locally
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache
